[package]
name = "harbs-bot"
version = "0.1.0"
authors = ["Henry Rocha <henryfr1@al.insper.edu.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.6"
dotenv = "0.15.0"
chrono = "0.4.11"
